// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "kubernetes:k8s.mariadb.com/v1alpha1:Backup":
		r = &Backup{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:BackupList":
		r = &BackupList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:BackupPatch":
		r = &BackupPatch{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:Connection":
		r = &Connection{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:ConnectionList":
		r = &ConnectionList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:ConnectionPatch":
		r = &ConnectionPatch{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:Database":
		r = &Database{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:DatabaseList":
		r = &DatabaseList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:DatabasePatch":
		r = &DatabasePatch{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:Grant":
		r = &Grant{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:GrantList":
		r = &GrantList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:GrantPatch":
		r = &GrantPatch{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:MariaDB":
		r = &MariaDB{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:MariaDBList":
		r = &MariaDBList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:MariaDBPatch":
		r = &MariaDBPatch{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:MaxScale":
		r = &MaxScale{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:MaxScaleList":
		r = &MaxScaleList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:MaxScalePatch":
		r = &MaxScalePatch{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:Restore":
		r = &Restore{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:RestoreList":
		r = &RestoreList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:RestorePatch":
		r = &RestorePatch{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:SqlJob":
		r = &SqlJob{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:SqlJobList":
		r = &SqlJobList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:SqlJobPatch":
		r = &SqlJobPatch{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:User":
		r = &User{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:UserList":
		r = &UserList{}
	case "kubernetes:k8s.mariadb.com/v1alpha1:UserPatch":
		r = &UserPatch{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := utilities.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"mariadb",
		"k8s.mariadb.com/v1alpha1",
		&module{version},
	)
}
