// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ImageCatalog is the Schema for the imagecatalogs API
type ImageCatalog struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput `pulumi:"metadata"`
	Spec     ImageCatalogSpecOutput  `pulumi:"spec"`
}

// NewImageCatalog registers a new resource with the given unique name, arguments, and options.
func NewImageCatalog(ctx *pulumi.Context,
	name string, args *ImageCatalogArgs, opts ...pulumi.ResourceOption) (*ImageCatalog, error) {
	if args == nil {
		args = &ImageCatalogArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("postgresql.cnpg.io/v1")
	args.Kind = pulumi.StringPtr("ImageCatalog")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ImageCatalog
	err := ctx.RegisterResource("kubernetes:postgresql.cnpg.io/v1:ImageCatalog", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetImageCatalog gets an existing ImageCatalog resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetImageCatalog(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ImageCatalogState, opts ...pulumi.ResourceOption) (*ImageCatalog, error) {
	var resource ImageCatalog
	err := ctx.ReadResource("kubernetes:postgresql.cnpg.io/v1:ImageCatalog", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ImageCatalog resources.
type imageCatalogState struct {
}

type ImageCatalogState struct {
}

func (ImageCatalogState) ElementType() reflect.Type {
	return reflect.TypeOf((*imageCatalogState)(nil)).Elem()
}

type imageCatalogArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	Spec     *ImageCatalogSpec  `pulumi:"spec"`
}

// The set of arguments for constructing a ImageCatalog resource.
type ImageCatalogArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     ImageCatalogSpecPtrInput
}

func (ImageCatalogArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*imageCatalogArgs)(nil)).Elem()
}

type ImageCatalogInput interface {
	pulumi.Input

	ToImageCatalogOutput() ImageCatalogOutput
	ToImageCatalogOutputWithContext(ctx context.Context) ImageCatalogOutput
}

func (*ImageCatalog) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageCatalog)(nil)).Elem()
}

func (i *ImageCatalog) ToImageCatalogOutput() ImageCatalogOutput {
	return i.ToImageCatalogOutputWithContext(context.Background())
}

func (i *ImageCatalog) ToImageCatalogOutputWithContext(ctx context.Context) ImageCatalogOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageCatalogOutput)
}

// ImageCatalogArrayInput is an input type that accepts ImageCatalogArray and ImageCatalogArrayOutput values.
// You can construct a concrete instance of `ImageCatalogArrayInput` via:
//
//	ImageCatalogArray{ ImageCatalogArgs{...} }
type ImageCatalogArrayInput interface {
	pulumi.Input

	ToImageCatalogArrayOutput() ImageCatalogArrayOutput
	ToImageCatalogArrayOutputWithContext(context.Context) ImageCatalogArrayOutput
}

type ImageCatalogArray []ImageCatalogInput

func (ImageCatalogArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ImageCatalog)(nil)).Elem()
}

func (i ImageCatalogArray) ToImageCatalogArrayOutput() ImageCatalogArrayOutput {
	return i.ToImageCatalogArrayOutputWithContext(context.Background())
}

func (i ImageCatalogArray) ToImageCatalogArrayOutputWithContext(ctx context.Context) ImageCatalogArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageCatalogArrayOutput)
}

// ImageCatalogMapInput is an input type that accepts ImageCatalogMap and ImageCatalogMapOutput values.
// You can construct a concrete instance of `ImageCatalogMapInput` via:
//
//	ImageCatalogMap{ "key": ImageCatalogArgs{...} }
type ImageCatalogMapInput interface {
	pulumi.Input

	ToImageCatalogMapOutput() ImageCatalogMapOutput
	ToImageCatalogMapOutputWithContext(context.Context) ImageCatalogMapOutput
}

type ImageCatalogMap map[string]ImageCatalogInput

func (ImageCatalogMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ImageCatalog)(nil)).Elem()
}

func (i ImageCatalogMap) ToImageCatalogMapOutput() ImageCatalogMapOutput {
	return i.ToImageCatalogMapOutputWithContext(context.Background())
}

func (i ImageCatalogMap) ToImageCatalogMapOutputWithContext(ctx context.Context) ImageCatalogMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageCatalogMapOutput)
}

type ImageCatalogOutput struct{ *pulumi.OutputState }

func (ImageCatalogOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageCatalog)(nil)).Elem()
}

func (o ImageCatalogOutput) ToImageCatalogOutput() ImageCatalogOutput {
	return o
}

func (o ImageCatalogOutput) ToImageCatalogOutputWithContext(ctx context.Context) ImageCatalogOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o ImageCatalogOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageCatalog) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ImageCatalogOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageCatalog) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o ImageCatalogOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *ImageCatalog) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o ImageCatalogOutput) Spec() ImageCatalogSpecOutput {
	return o.ApplyT(func(v *ImageCatalog) ImageCatalogSpecOutput { return v.Spec }).(ImageCatalogSpecOutput)
}

type ImageCatalogArrayOutput struct{ *pulumi.OutputState }

func (ImageCatalogArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ImageCatalog)(nil)).Elem()
}

func (o ImageCatalogArrayOutput) ToImageCatalogArrayOutput() ImageCatalogArrayOutput {
	return o
}

func (o ImageCatalogArrayOutput) ToImageCatalogArrayOutputWithContext(ctx context.Context) ImageCatalogArrayOutput {
	return o
}

func (o ImageCatalogArrayOutput) Index(i pulumi.IntInput) ImageCatalogOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ImageCatalog {
		return vs[0].([]*ImageCatalog)[vs[1].(int)]
	}).(ImageCatalogOutput)
}

type ImageCatalogMapOutput struct{ *pulumi.OutputState }

func (ImageCatalogMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ImageCatalog)(nil)).Elem()
}

func (o ImageCatalogMapOutput) ToImageCatalogMapOutput() ImageCatalogMapOutput {
	return o
}

func (o ImageCatalogMapOutput) ToImageCatalogMapOutputWithContext(ctx context.Context) ImageCatalogMapOutput {
	return o
}

func (o ImageCatalogMapOutput) MapIndex(k pulumi.StringInput) ImageCatalogOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ImageCatalog {
		return vs[0].(map[string]*ImageCatalog)[vs[1].(string)]
	}).(ImageCatalogOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ImageCatalogInput)(nil)).Elem(), &ImageCatalog{})
	pulumi.RegisterInputType(reflect.TypeOf((*ImageCatalogArrayInput)(nil)).Elem(), ImageCatalogArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ImageCatalogMapInput)(nil)).Elem(), ImageCatalogMap{})
	pulumi.RegisterOutputType(ImageCatalogOutput{})
	pulumi.RegisterOutputType(ImageCatalogArrayOutput{})
	pulumi.RegisterOutputType(ImageCatalogMapOutput{})
}
