// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "kubernetes:kargo.akuity.io/v1alpha1:ClusterPromotionTask":
		r = &ClusterPromotionTask{}
	case "kubernetes:kargo.akuity.io/v1alpha1:ClusterPromotionTaskList":
		r = &ClusterPromotionTaskList{}
	case "kubernetes:kargo.akuity.io/v1alpha1:ClusterPromotionTaskPatch":
		r = &ClusterPromotionTaskPatch{}
	case "kubernetes:kargo.akuity.io/v1alpha1:Freight":
		r = &Freight{}
	case "kubernetes:kargo.akuity.io/v1alpha1:FreightList":
		r = &FreightList{}
	case "kubernetes:kargo.akuity.io/v1alpha1:FreightPatch":
		r = &FreightPatch{}
	case "kubernetes:kargo.akuity.io/v1alpha1:Project":
		r = &Project{}
	case "kubernetes:kargo.akuity.io/v1alpha1:ProjectConfig":
		r = &ProjectConfig{}
	case "kubernetes:kargo.akuity.io/v1alpha1:ProjectConfigList":
		r = &ProjectConfigList{}
	case "kubernetes:kargo.akuity.io/v1alpha1:ProjectConfigPatch":
		r = &ProjectConfigPatch{}
	case "kubernetes:kargo.akuity.io/v1alpha1:ProjectList":
		r = &ProjectList{}
	case "kubernetes:kargo.akuity.io/v1alpha1:ProjectPatch":
		r = &ProjectPatch{}
	case "kubernetes:kargo.akuity.io/v1alpha1:Promotion":
		r = &Promotion{}
	case "kubernetes:kargo.akuity.io/v1alpha1:PromotionList":
		r = &PromotionList{}
	case "kubernetes:kargo.akuity.io/v1alpha1:PromotionPatch":
		r = &PromotionPatch{}
	case "kubernetes:kargo.akuity.io/v1alpha1:PromotionTask":
		r = &PromotionTask{}
	case "kubernetes:kargo.akuity.io/v1alpha1:PromotionTaskList":
		r = &PromotionTaskList{}
	case "kubernetes:kargo.akuity.io/v1alpha1:PromotionTaskPatch":
		r = &PromotionTaskPatch{}
	case "kubernetes:kargo.akuity.io/v1alpha1:Stage":
		r = &Stage{}
	case "kubernetes:kargo.akuity.io/v1alpha1:StageList":
		r = &StageList{}
	case "kubernetes:kargo.akuity.io/v1alpha1:StagePatch":
		r = &StagePatch{}
	case "kubernetes:kargo.akuity.io/v1alpha1:Warehouse":
		r = &Warehouse{}
	case "kubernetes:kargo.akuity.io/v1alpha1:WarehouseList":
		r = &WarehouseList{}
	case "kubernetes:kargo.akuity.io/v1alpha1:WarehousePatch":
		r = &WarehousePatch{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := utilities.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"kargo",
		"kargo.akuity.io/v1alpha1",
		&module{version},
	)
}
